apiVersion: v1
kind: Service
metadata:
  labels:
    component: flower
  name: flower-service
spec:
  ports:
  - port: 5555
  selector:
    app: taskQueue
    component: flower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
  labels:
    app: taskQueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskQueue
  template:
    metadata:
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
      - name: flower
        image: testing_local_flower
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555

